### ISSUE TITLE
关于https

### ISSUE THREAD

**Issue by NitroCao** [qinyuanpei/hexo-tag-cloudmusic#1]
由于网易云音乐都是http，我的网站全站启用https，导致播放器不能加载。这个问题应该不能通过插件解决吧。。。

**Comment by qinyuanpei** [comment]
这个问题的确是无法解决:(，这个项目是当时即兴之作，代码特别混乱，明白怎么实现就好了

**Comment by flaski** [comment]
https的问题很好解决啊，就是在生成的链接上直接改成https就可以了

**Comment by NitroCao** [comment]
@flaski 要是真的这么简单，我还用得着跑这儿来问作者么。。。建议你先去了解了解https

**Comment by qinyuanpei** [comment]
@flaski HTTPS需要服务器支持，而Github Pages提供的仅仅是一个静态页面托管服务而已，所以如果你想采用HTTPS就应该使用自己的服务器啊，可以参考Hexo这个博客系统如何实现HTTPS的相关内容，这个问题你我都是无法解决的。
