### ISSUE TITLE
always autoplay

### ISSUE THREAD

**Issue by liuxueyang** [qinyuanpei/hexo-tag-cloudmusic#2]
Thanks for you plugin. ;-)

I use your configuration in the README.md of your repo. I tried to add it to the _config.yml of hexo root directory or to the _config.yml of the theme I used. I set the `autoPlay: 0` in the config, but it still autoplay the music when I enter my blog.

How to solve that? my configuration is wrong. Thanks in advance.

**Comment by qinyuanpei** [comment]
这个你具体看看网易云音乐里生成的外链播放器的代码即可，我记得autoplay:0就表示关闭自动播放啊，或许是网易云音乐改变了相关接口吧，喜欢就好_^_^_

**Comment by liuxueyang** [comment]
嗯，看了生成的html，貌似没错，还是不知道为什么 😂 😂
