### ISSUE TITLE
请问能不能换一下应用形式呢~

### ISSUE THREAD

**Issue by wanzhiyu** [qinyuanpei/hexo-tag-cloudmusic#3]
现在要这样{%cloudmusic 一串数字%}才能调用，请问能不能做到直接复制链接就可以自动识别呢，比如这样：http://music.163.com/#/m/song?id=5047863&userid=64871628。谢谢！

**Comment by qinyuanpei** [comment]
首先，{ }这种形式是Hexo定义的标签插件，基于这种机制，我们可以实现各种各样的“短代码”到HTML的转换，你直接输入一个链接，它就是个链接啊，如果这个要帮你识别为网易云音乐外链，并且还要转换为HTML代码，那么对一般的链接应该怎么处理呢？

**Comment by qinyuanpei** [comment]
这个我觉得要配合编辑器来做吧！
