### ISSUE TITLE
请问{% cloudmusic 20744792 %}是插入在那里？

### ISSUE THREAD

**Issue by weqeo** [qinyuanpei/hexo-tag-cloudmusic#4]

**Comment by qinyuanpei** [comment]
博客里就可以啊

**Comment by weqeo** [comment]
@qinyuanpei 哦，我理解错了。我是想搞一个在主页中的音乐插件，现在我是这么整的：http://weqeo.com/2016/10/11/Hexo%E4%B8%AD%E6%92%AD%E6%94%BE%E7%BD%91%E6%98%93%E4%BA%91%E9%9F%B3%E4%B9%90%E7%9A%84%E5%AE%9E%E8%B7%B5/
不过还是非常感谢！
