### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by asuna** [qinyuanpei/hexo-tag-cloudmusic#7]
感谢作者提供这个插件，在此提供一些小建议，希望能够采纳。 :)

1. 使用相对路径自动判断http/https
将`http://http://music.163.com`改为`//music.163.com`。

2. 默认试用iframe
flash形式已被adobe宣布放弃，缓刑3年，且目前html5越来越流行。

3. 默认禁止自动播放
应该有不少人反感自动播放，因此建议默认不要自动播放。

**Comment by qinyuanpei** [comment]
事实上Https的问题有朋友之前提到过，但这个问题基本上是无解的，因为Https是否能被支持取决于网易，并不是我们由我们的博客来决定的，HTML5的趋势没有问题，手机浏览器兼容性是问题，默认播放感觉略奇怪啊

**Comment by asuna** [comment]
默认播放的问题，我测试在_config.yml中设置`autoPlay: '0'`就可以生效，但`autoPlay： 0`无效。
或者修改index.js中的`var autoPlay = config.autoPlay || 1;`为`var autoPlay = config.autoPlay.toString() || 1;`
也许是数据类型的问题？
没怎么学过开发。。。希望能提供点帮助吧。

**Comment by qinyuanpei** [comment]
这个没测试，垃圾JS

在 2017-08-22 09:39:34，asuna <notifications@github.com> 写道：


默认播放的问题，我测试在_config.yml中设置autoPlay: '0'就可以生效，但autoPlay： 0无效。
或者修改index.js中的var autoPlay = config.autoPlay.toString() || 1;为var autoPlay = config.autoPlay.toString() || 1;
也许是数据类型的问题？
没怎么学过开发。。。希望能提供点帮助吧。
